/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as LojaIdRouteImport } from './routes/loja.$id'
import { Route as AuthenticatedSegurancaRouteImport } from './routes/_authenticated/seguranca'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedLojistaCrmRouteImport } from './routes/_authenticated/lojista-crm'
import { Route as AuthenticatedLojistaRouteImport } from './routes/_authenticated/lojista'
import { Route as AuthenticatedIdiomaRouteImport } from './routes/_authenticated/idioma'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedEnderecosRouteImport } from './routes/_authenticated/enderecos'
import { Route as AuthenticatedEditarPerfilRouteImport } from './routes/_authenticated/editar-perfil'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedAfiliadosRouteImport } from './routes/_authenticated/afiliados'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin-crm'
import { Route as AuthenticatedLojistaIndexRouteImport } from './routes/_authenticated/lojista.index'
import { Route as AuthenticatedLojistaProdutosRouteImport } from './routes/_authenticated/lojista.produtos'
import { Route as AuthenticatedLojistaPedidosRouteImport } from './routes/_authenticated/lojista.pedidos'
import { Route as AuthenticatedLojistaDashboardRouteImport } from './routes/_authenticated/lojista.dashboard'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIdRoute = LojaIdRouteImport.update({
  id: '/loja/$id',
  path: '/loja/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSegurancaRoute = AuthenticatedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojistaCrmRoute = AuthenticatedLojistaCrmRouteImport.update({
  id: '/lojista-crm',
  path: '/lojista-crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojistaRoute = AuthenticatedLojistaRouteImport.update({
  id: '/lojista',
  path: '/lojista',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdiomaRoute = AuthenticatedIdiomaRouteImport.update({
  id: '/idioma',
  path: '/idioma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnderecosRoute = AuthenticatedEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditarPerfilRoute =
  AuthenticatedEditarPerfilRouteImport.update({
    id: '/editar-perfil',
    path: '/editar-perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAfiliadosRoute = AuthenticatedAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/admin-crm',
  path: '/admin-crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojistaIndexRoute =
  AuthenticatedLojistaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLojistaRoute,
  } as any)
const AuthenticatedLojistaProdutosRoute =
  AuthenticatedLojistaProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedLojistaRoute,
  } as any)
const AuthenticatedLojistaPedidosRoute =
  AuthenticatedLojistaPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedLojistaRoute,
  } as any)
const AuthenticatedLojistaDashboardRoute =
  AuthenticatedLojistaDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedLojistaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin-crm': typeof AuthenticatedAdminCrmRoute
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/enderecos': typeof AuthenticatedEnderecosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/idioma': typeof AuthenticatedIdiomaRoute
  '/lojista': typeof AuthenticatedLojistaRouteWithChildren
  '/lojista-crm': typeof AuthenticatedLojistaCrmRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/loja/$id': typeof LojaIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/lojista/dashboard': typeof AuthenticatedLojistaDashboardRoute
  '/lojista/pedidos': typeof AuthenticatedLojistaPedidosRoute
  '/lojista/produtos': typeof AuthenticatedLojistaProdutosRoute
  '/lojista/': typeof AuthenticatedLojistaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin-crm': typeof AuthenticatedAdminCrmRoute
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/enderecos': typeof AuthenticatedEnderecosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/idioma': typeof AuthenticatedIdiomaRoute
  '/lojista-crm': typeof AuthenticatedLojistaCrmRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/loja/$id': typeof LojaIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/lojista/dashboard': typeof AuthenticatedLojistaDashboardRoute
  '/lojista/pedidos': typeof AuthenticatedLojistaPedidosRoute
  '/lojista/produtos': typeof AuthenticatedLojistaProdutosRoute
  '/lojista': typeof AuthenticatedLojistaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin-crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/afiliados': typeof AuthenticatedAfiliadosRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/_authenticated/enderecos': typeof AuthenticatedEnderecosRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/idioma': typeof AuthenticatedIdiomaRoute
  '/_authenticated/lojista': typeof AuthenticatedLojistaRouteWithChildren
  '/_authenticated/lojista-crm': typeof AuthenticatedLojistaCrmRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/seguranca': typeof AuthenticatedSegurancaRoute
  '/loja/$id': typeof LojaIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/_authenticated/lojista/dashboard': typeof AuthenticatedLojistaDashboardRoute
  '/_authenticated/lojista/pedidos': typeof AuthenticatedLojistaPedidosRoute
  '/_authenticated/lojista/produtos': typeof AuthenticatedLojistaProdutosRoute
  '/_authenticated/lojista/': typeof AuthenticatedLojistaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/carrinho'
    | '/chat'
    | '/checkout'
    | '/home'
    | '/login'
    | '/lojas'
    | '/perfil'
    | '/sitemap.xml'
    | '/termos'
    | '/admin-crm'
    | '/afiliados'
    | '/compras'
    | '/editar-perfil'
    | '/enderecos'
    | '/favoritos'
    | '/idioma'
    | '/lojista'
    | '/lojista-crm'
    | '/pagamentos'
    | '/seguranca'
    | '/loja/$id'
    | '/produto/$id'
    | '/lojista/dashboard'
    | '/lojista/pedidos'
    | '/lojista/produtos'
    | '/lojista/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/carrinho'
    | '/chat'
    | '/checkout'
    | '/home'
    | '/login'
    | '/lojas'
    | '/perfil'
    | '/sitemap.xml'
    | '/termos'
    | '/admin-crm'
    | '/afiliados'
    | '/compras'
    | '/editar-perfil'
    | '/enderecos'
    | '/favoritos'
    | '/idioma'
    | '/lojista-crm'
    | '/pagamentos'
    | '/seguranca'
    | '/loja/$id'
    | '/produto/$id'
    | '/lojista/dashboard'
    | '/lojista/pedidos'
    | '/lojista/produtos'
    | '/lojista'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ajuda'
    | '/cadastro'
    | '/carrinho'
    | '/chat'
    | '/checkout'
    | '/home'
    | '/login'
    | '/lojas'
    | '/perfil'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/admin-crm'
    | '/_authenticated/afiliados'
    | '/_authenticated/compras'
    | '/_authenticated/editar-perfil'
    | '/_authenticated/enderecos'
    | '/_authenticated/favoritos'
    | '/_authenticated/idioma'
    | '/_authenticated/lojista'
    | '/_authenticated/lojista-crm'
    | '/_authenticated/pagamentos'
    | '/_authenticated/seguranca'
    | '/loja/$id'
    | '/produto/$id'
    | '/_authenticated/lojista/dashboard'
    | '/_authenticated/lojista/pedidos'
    | '/_authenticated/lojista/produtos'
    | '/_authenticated/lojista/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  LojasRoute: typeof LojasRoute
  PerfilRoute: typeof PerfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  LojaIdRoute: typeof LojaIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$id': {
      id: '/loja/$id'
      path: '/loja/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof LojaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seguranca': {
      id: '/_authenticated/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AuthenticatedSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojista-crm': {
      id: '/_authenticated/lojista-crm'
      path: '/lojista-crm'
      fullPath: '/lojista-crm'
      preLoaderRoute: typeof AuthenticatedLojistaCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojista': {
      id: '/_authenticated/lojista'
      path: '/lojista'
      fullPath: '/lojista'
      preLoaderRoute: typeof AuthenticatedLojistaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/idioma': {
      id: '/_authenticated/idioma'
      path: '/idioma'
      fullPath: '/idioma'
      preLoaderRoute: typeof AuthenticatedIdiomaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enderecos': {
      id: '/_authenticated/enderecos'
      path: '/enderecos'
      fullPath: '/enderecos'
      preLoaderRoute: typeof AuthenticatedEnderecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editar-perfil': {
      id: '/_authenticated/editar-perfil'
      path: '/editar-perfil'
      fullPath: '/editar-perfil'
      preLoaderRoute: typeof AuthenticatedEditarPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/afiliados': {
      id: '/_authenticated/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AuthenticatedAfiliadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-crm': {
      id: '/_authenticated/admin-crm'
      path: '/admin-crm'
      fullPath: '/admin-crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojista/': {
      id: '/_authenticated/lojista/'
      path: '/'
      fullPath: '/lojista/'
      preLoaderRoute: typeof AuthenticatedLojistaIndexRouteImport
      parentRoute: typeof AuthenticatedLojistaRoute
    }
    '/_authenticated/lojista/produtos': {
      id: '/_authenticated/lojista/produtos'
      path: '/produtos'
      fullPath: '/lojista/produtos'
      preLoaderRoute: typeof AuthenticatedLojistaProdutosRouteImport
      parentRoute: typeof AuthenticatedLojistaRoute
    }
    '/_authenticated/lojista/pedidos': {
      id: '/_authenticated/lojista/pedidos'
      path: '/pedidos'
      fullPath: '/lojista/pedidos'
      preLoaderRoute: typeof AuthenticatedLojistaPedidosRouteImport
      parentRoute: typeof AuthenticatedLojistaRoute
    }
    '/_authenticated/lojista/dashboard': {
      id: '/_authenticated/lojista/dashboard'
      path: '/dashboard'
      fullPath: '/lojista/dashboard'
      preLoaderRoute: typeof AuthenticatedLojistaDashboardRouteImport
      parentRoute: typeof AuthenticatedLojistaRoute
    }
  }
}

interface AuthenticatedLojistaRouteChildren {
  AuthenticatedLojistaDashboardRoute: typeof AuthenticatedLojistaDashboardRoute
  AuthenticatedLojistaPedidosRoute: typeof AuthenticatedLojistaPedidosRoute
  AuthenticatedLojistaProdutosRoute: typeof AuthenticatedLojistaProdutosRoute
  AuthenticatedLojistaIndexRoute: typeof AuthenticatedLojistaIndexRoute
}

const AuthenticatedLojistaRouteChildren: AuthenticatedLojistaRouteChildren = {
  AuthenticatedLojistaDashboardRoute: AuthenticatedLojistaDashboardRoute,
  AuthenticatedLojistaPedidosRoute: AuthenticatedLojistaPedidosRoute,
  AuthenticatedLojistaProdutosRoute: AuthenticatedLojistaProdutosRoute,
  AuthenticatedLojistaIndexRoute: AuthenticatedLojistaIndexRoute,
}

const AuthenticatedLojistaRouteWithChildren =
  AuthenticatedLojistaRoute._addFileChildren(AuthenticatedLojistaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAfiliadosRoute: typeof AuthenticatedAfiliadosRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedEditarPerfilRoute: typeof AuthenticatedEditarPerfilRoute
  AuthenticatedEnderecosRoute: typeof AuthenticatedEnderecosRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedIdiomaRoute: typeof AuthenticatedIdiomaRoute
  AuthenticatedLojistaRoute: typeof AuthenticatedLojistaRouteWithChildren
  AuthenticatedLojistaCrmRoute: typeof AuthenticatedLojistaCrmRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedSegurancaRoute: typeof AuthenticatedSegurancaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAfiliadosRoute: AuthenticatedAfiliadosRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedEditarPerfilRoute: AuthenticatedEditarPerfilRoute,
  AuthenticatedEnderecosRoute: AuthenticatedEnderecosRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedIdiomaRoute: AuthenticatedIdiomaRoute,
  AuthenticatedLojistaRoute: AuthenticatedLojistaRouteWithChildren,
  AuthenticatedLojistaCrmRoute: AuthenticatedLojistaCrmRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedSegurancaRoute: AuthenticatedSegurancaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AjudaRoute: AjudaRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  LojasRoute: LojasRoute,
  PerfilRoute: PerfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  LojaIdRoute: LojaIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
